version: "3.9"
services:
    poc-core-db:
        image: postgres
        environment:
            POSTGRES_USER: valtimo
            POSTGRES_PASSWORD: valtimo
        ports:
            - "15432:5432"

    # To fix 'Out of sort memory, consider increasing server sort buffer size' adjust value of 'sort-buffer-size'
#    poc-core-db:
#        image: mysql:8-oracle
#        cap_add:
#            - SYS_NICE  # CAP_SYS_NICE
#        command:
#            --collation-server=utf8mb4_unicode_ci
#            --default-authentication-plugin=mysql_native_password
#            --information-schema-stats-expiry=0
#            --innodb-flush-method=O_DIRECT
#            --lower-case-table-names=1
#            --sort-buffer-size=5M
#            --sql-mode=NO_ENGINE_SUBSTITUTION
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_ROOT_PASSWORD: password
#            MYSQL_DATABASE: valtimo-core
#            MYSQL_USER: valtimo
#            MYSQL_PASSWORD: password
#        volumes:
#            - valtimo-core-db-data:/var/lib/mysql # persist data even if container shuts down

    poc-core-keycloak-db:
        image: mysql:8-oracle
        ports:
            - "3307:3306"
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        command:
            --connect-timeout=40000
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password

    poc-core-keycloak:
        image: keycloak/keycloak:20.0
        ports:
            - "8082:8080"
        depends_on:
            - poc-core-keycloak-db
        environment:
            KC_HOSTNAME_URL: http://localhost:8082/auth/
            KC_HOSTNAME_ADMIN_URL: http://localhost:8082/auth/
            KC_HTTP_RELATIVE_PATH: "/auth/"
            KC_DB: mysql
            KC_DB_URL: jdbc:mysql://poc-core-keycloak-db:3306/keycloak?characterEncoding=UTF-8
            KC_DB_PASSWORD: password
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTP_ENABLED: "true"
            KC_HEALTH_ENABLED: "true"
            KC_LOG_LEVEL: info
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8082/auth/health/ready" ]
            interval: 15s
            timeout: 2s
            retries: 15
        command: [ "start --import-realm" ]
        volumes:
            - ./docker/keycloak:/opt/keycloak/data/import/

volumes:
    poc-core-db-data: #enabled persistence
